dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
install:
# update mvnw
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarqube:
    organization: 308309
    token: $SONARQUBE_TOKEN
    branches:
    - master
script:
 - sonar-scanner
env:
  global:
  - secure: urPqQ7ntFER/iyPsz3KQbNFupyXVyQszsGZ89Zq2Se8/TX97XywnKZtaLqm+XujW5/ELIJPaROKSFlpdAoCRXJUrmw3sEjKnbN/7ou9vh96jwPreIriPkGPQ+RjryZYyYx0RztVXVwwrJjnpcp/nCtv0pczdwDUSndA+mjYdaKj5R7+nFQbMfnSKdvKZoJ96iylVZgVPGpV0larxMCEpXmG+u0v3bb6I/XwHNcdrrjtkqUKOgMbZMmZbB11Aoi9s0502PAc+253er63o8L9pG4aOSkTorvqvG9t98B/rorBSu0SMDwuNIQ/OkFF1DLPZY84VfLZsTFFV16uVw8GyghAenEd0zUaWEJrLfLFHwi/Z4fXUB0Kkg/AisyqH7nRIlJLjrot2Uhnm5ZqcCA3/UJUJtuc5n7TG8UqLh1ZPpY6dXwqXYC1Jut5nkGE/PDi0xHlpSlvF2XStcZowGnkEJ5JzJqZgRCOfH1Uu3FQzNFWt0w3OtUPSpMJeYrHkaGIACvO/viv+CsjeCeyYIDjq4NWYICmMsiSbvfytcR6vIKfpaNWwlgf20Euzr+ykN9inMeednr+cAl5FbufPxtKrWrvzbwivdJHKrUdc5auqtxPwEptqSgQ0zFZpXo/s1sb+LyAOyxnMaD7iMnFMA1fbHhBHY3VnMvMZzuhyQ2DTrgY=
  - secure: UPRT0qSG5NLHPk13QtR+nF5n8IsyHtaDB+C2iB+b60pc9845D3ivhJ7iG8DYe9xVPr7DWnCjiDsVUShMAiFszXWeY4mqJaux4l8CUEiGD0Bne7r38Q5mDWtQbmirCR9FWEzgjzzlRSUCOqmwaXo6Om0YIIHcRuLaQBvvs+xfBnwBxn+IeQcFCVyeYgh8+nirC00hDAVIO4p8cvw4C6UZAjMPHCiMwKenObMcNDy2FHqAGar0D0acSOiTaeP85HX+ajI89pzvXePGqGkmMdd6kw9xAMAeIEXtb3YUXIme8S+fyMU9F7YAw9NnYfQ1zReV1tkqtIZ/obdq+MjAc0jRP2CUIx6LgZ/qEluKvw3QyISm96bXMzLeP7z9/4w/O4PdMUkMERlNcOMsEVt1PNYZdgk9P8uZDmstqZz5duEs9fd2It/2YT5oVVIt3LwH5Gvhrm6fEKF1eSeR172vxQshzK4seQ09vy2PJYM2LnXksamRyA11kGjn5agnipZxnkX1IxxIspAbp3E3xW8EtvYIZuv08vkNd7BiBortggP4UHF4QuigKaDWMrtn/O172RFOuLSq58E8iwPWGljSTTcRZJhrnWdxB92MiOAeyMXuw3hrjmtLc8sFj9XIpWjuzRRvOAXaOt6e+nIkvGT64nkM5v9Fkj1FWQ1E7kDEnZRzwEc=
